name: gray
favicon: null
layout_spectrum: 0.0575268198736012
typography_spectrum: 0.45856891851872206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#757c86'
    - '#212429'
    - '#2c4c1e'
    - '#6a1024'
    - '#ae9c88'
  brandStrength: 0.8008716038893908
  lightness: 0.5876750755123794
  saturation: 0.7615530150942504
  rhythmicContrast: 0.9244674621149898
purpose: []
